# -*- coding: utf-8 -*-
"""cv_lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzFAVR4qkmTazVn9Pgq-X-N8PsZGKbtX
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #
  plt.subplot(2,2,1)
  plt.imshow(original,cmap = 'gray')
  plt.title('Original ')
  plt.axis('off')
  #
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap = 'gray')
  plt.title('Blur 3')
  plt.axis('off')
  #
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap = 'gray')
  plt.title('Blur 5')
  plt.axis('off')
  #
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap = 'gray')
  plt.title('Blur 7')
  plt.axis('off')
  #
  plt.tight_layout()
  plt.show()

# Fix: Provide a valid image path. For demonstration, we'll use a placeholder 'blur.jpg'.
# You need to ensure 'blur.jpg' exists in your environment or provide its full path.
image = cv2.imread('/content/drive/MyDrive/Blurimg.jpg',0)

if image is None:
    print("Error: Could not load image 'blur.jpg'. Please ensure it is uploaded or the path is correct.")
else:
    print(f"Image 'blur.jpg' loaded successfully with shape: {image.shape}")
    plt.imshow(image, cmap='gray')
    plt.title('Loaded Image: blur.jpg')
    plt.axis('off')
    plt.show()

# The GaussianBlur calls will only work if `image` is not None.
# Placing them inside the else block ensures `image` is valid.
if image is not None:
    blur3 = cv2.GaussianBlur(image, (3, 3), 0)
    blur5 = cv2.GaussianBlur(image, (5, 5), 0)
    blur7 = cv2.GaussianBlur(image, (7, 7), 0)

    show_comparison(image, blur3, blur5, blur7)
    import numpy as np
    kernel = np.ones((5,5),np.float32)/25

    plt.show()
    dst = cv2.filter2D(image,-1,kernel)
    show_comparison(image,dst,dst,dst)

